export const AVAILABLE_SKILLS = [
  '3D PRINTING CONCEPTS, DESIGN AND PRINTING',
  'Adobe Illustrator',
  'Adobe Indesign',
  'Adobe Photoshop',
  'Android Studio',
  'Angular',
  'AWS',
  'Azure',
  'BIM CONCEPTS WITH MEP AND PRODUCT DESIGN',
  'BIM FOR ARCHITECTURE',
  'BIM FOR CONSTRUCTION',
  'BIM FOR HIGHWAY ENGINEERING',
  'BIM FOR STRUCTURES',
  'Business Management',
  'C++',
  'CakePHP',
  'Canva',
  'Cassandra',
  'Circuit Design',
  'Cloud access control',
  'CodeIgniter',
  'Computer Vision',
  'CSS',
  'D3.js',
  'Data Encryption',
  'Data Modeling',
  'Data Visualization',
  'Database Design',
  'Design with FPGA',
  'DevOps',
  'DHCP',
  'Digital Design',
  'Docker',
  'Economics',
  'Embedded Systems',
  'Figma',
  'FilamentPHP',
  'Finance',
  'Firewall Configuration',
  'Flutter',
  'Git',
  'Godot',
  'Google Cloud',
  'HTML',
  'IaaS',
  'Indexing',
  'Intelligent Machines',
  'Interior and Exterior Design',
  'IoT',
  'Java',
  'JavaScript',
  'Keras',
  'Kotlin',
  'Kubernetes',
  'LAN',
  'Laravel',
  'Layout Design',
  'Machine Learning',
  'Manufacturing',
  'Marketing',
  'MongoDB',
  'MySQL',
  'Natural Language Processing',
  'Network Architecture',
  'Node.js',
  'NoSQL',
  'Objective-C',
  'PaaS',
  'PHP',
  'Physical Design',
  'PostgreSQL',
  'Power BI',
  'Product Design & 3D Printing',
  'Product Design & Manufacturing',
  'Python',
  'PyTorch',
  'React',
  'React.js',
  'Ruby on Rails',
  'SaaS',
  'Scikit-learn',
  'SEO',
  'SQL',
  'Statistical Analysis',
  'Swift',
  'Tableau',
  'TCP/IP',
  'TensorFlow',
  'TypeScript',
  'UI/UX',
  'Verification & Validations',
  'VLSI Design',
  'VPNs',
  'Vue.js',
  'WAN',
  'WordPress',
  'Xamarin',
];

// Skill matching keywords
export const SKILL_KEYWORDS: Record<string, string[]> = {
  'React': ['react', 'hooks', 'state management', 'jsx'],
  'React.js': ['react', 'hooks', 'state management', 'jsx'],
  'JavaScript': ['javascript', 'js', 'react', 'vue', 'angular', 'node', 'es6'],
  'TypeScript': ['typescript', 'ts', 'react', 'vue', 'angular'],
  'Node.js': ['node', 'express', 'backend', 'server'],
  'Python': ['python', 'django', 'flask', 'fastapi', 'webscraping', 'automation'],
  'Java': ['java', 'spring', 'backend'],
  'C++': ['c++', 'cpp', 'cpp'],
  'CSS': ['css', 'styling', 'layout', 'responsive', 'tailwind', 'bootstrap'],
  'HTML': ['html', 'markup', 'frontend', 'web'],
  'Angular': ['angular', 'typescript', 'frontend'],
  'Vue.js': ['vue', 'frontend', 'javascript'],
  'Database Design': ['database', 'sql', 'schema', 'modeling'],
  'MongoDB': ['mongodb', 'nosql', 'database', 'json'],
  'MySQL': ['mysql', 'sql', 'database', 'relational'],
  'PostgreSQL': ['postgresql', 'sql', 'database', 'relational'],
  'Git': ['git', 'version control', 'github', 'gitlab', 'bitbucket'],
  'Docker': ['docker', 'container', 'containerization', 'kubernetes'],
  'Kubernetes': ['kubernetes', 'k8s', 'orchestration', 'container'],
  'DevOps': ['devops', 'deployment', 'ci/cd', 'pipeline'],
  'AWS': ['aws', 'amazon', 'cloud'],
  'Azure': ['azure', 'microsoft', 'cloud'],
  'Google Cloud': ['gcp', 'google cloud', 'firebase'],
  'Machine Learning': ['machine learning', 'ml', 'predict', 'training'],
  'Python': ['python', 'ml', 'data science', 'tensorflow', 'keras', 'pytorch'],
  'TensorFlow': ['tensorflow', 'machine learning', 'deep learning'],
  'PyTorch': ['pytorch', 'machine learning', 'deep learning'],
  'Keras': ['keras', 'neural network', 'deep learning'],
  'Scikit-learn': ['scikit', 'sklearn', 'machine learning'],
  'Natural Language Processing': ['nlp', 'language', 'text processing'],
  'Computer Vision': ['computer vision', 'cv', 'image processing', 'opencv'],
  'Data Visualization': ['visualization', 'chart', 'graph', 'data viz'],
  'Power BI': ['power bi', 'bi', 'dashboard', 'analytics'],
  'Tableau': ['tableau', 'visualization', 'dashboard', 'analytics'],
  'D3.js': ['d3', 'visualization', 'charts', 'graphs'],
  'UI/UX': ['ui', 'ux', 'design', 'user interface', 'user experience'],
  'Figma': ['figma', 'design', 'prototyping', 'ui'],
  'Adobe Photoshop': ['photoshop', 'psd', 'image editing', 'design'],
  'Adobe Illustrator': ['illustrator', 'vector', 'graphics', 'design'],
  'Adobe Indesign': ['indesign', 'layout', 'publishing', 'design'],
  'Canva': ['canva', 'design', 'template'],
  '3D PRINTING CONCEPTS, DESIGN AND PRINTING': ['3d printing', '3d design', 'stl', 'cad', 'additive'],
  'Product Design & 3D Printing': ['product design', '3d printing', 'cad'],
  'Product Design & Manufacturing': ['product design', 'manufacturing', 'design'],
  'BIM CONCEPTS WITH MEP AND PRODUCT DESIGN': ['bim', 'mep', 'revit', 'product'],
  'BIM FOR ARCHITECTURE': ['bim', 'architecture', 'revit', 'archicad'],
  'BIM FOR CONSTRUCTION': ['bim', 'construction', 'revit'],
  'BIM FOR STRUCTURES': ['bim', 'structure', 'revit', 'structural'],
  'BIM FOR HIGHWAY ENGINEERING': ['bim', 'highway', 'civil', 'engineering'],
  'Interior and Exterior Design': ['interior', 'exterior', 'design', 'architecture'],
  'Layout Design': ['layout', 'design', 'composition'],
  'Circuit Design': ['circuit', 'electronics', 'pcb', 'design'],
  'Embedded Systems': ['embedded', 'microcontroller', 'firmware', 'iot'],
  'Digital Design': ['digital', 'design', 'electronic'],
  'Design with FPGA': ['fpga', 'vhdl', 'verilog', 'hardware'],
  'VLSI Design': ['vlsi', 'verilog', 'vhdl', 'chip'],
  'IoT': ['iot', 'internet of things', 'sensor', 'embedded'],
  'Network Architecture': ['network', 'architecture', 'tcp', 'ip'],
  'TCP/IP': ['tcp', 'ip', 'network', 'protocol'],
  'LAN': ['lan', 'network', 'local area'],
  'WAN': ['wan', 'network', 'wide area'],
  'Firewall Configuration': ['firewall', 'security', 'network'],
  'Data Encryption': ['encryption', 'security', 'crypto'],
  'Cloud access control': ['cloud', 'access control', 'security'],
  'VPNs': ['vpn', 'network', 'security'],
  'DHCP': ['dhcp', 'network', 'protocol'],
  'Laravel': ['laravel', 'php', 'framework', 'web'],
  'PHP': ['php', 'web', 'backend', 'server'],
  'CakePHP': ['cakephp', 'php', 'framework'],
  'CodeIgniter': ['codeigniter', 'php', 'framework'],
  'FilamentPHP': ['filament', 'php', 'admin'],
  'Ruby on Rails': ['rails', 'ruby', 'framework', 'web'],
  'WordPress': ['wordpress', 'cms', 'php', 'web'],
  'Cassandra': ['cassandra', 'database', 'nosql', 'distributed'],
  'NoSQL': ['nosql', 'database', 'mongodb', 'cassandra'],
  'SQL': ['sql', 'database', 'query', 'relational'],
  'Data Modeling': ['data modeling', 'database', 'design'],
  'Indexing': ['indexing', 'database', 'performance'],
  'Business Management': ['business', 'management', 'leadership'],
  'Marketing': ['marketing', 'seo', 'promotion'],
  'SEO': ['seo', 'search engine', 'marketing', 'optimization'],
  'Finance': ['finance', 'accounting', 'business'],
  'Economics': ['economics', 'business', 'finance'],
  'Physical Design': ['physical design', 'layout', 'testing'],
  'Verification & Validations': ['verification', 'validation', 'testing', 'qa'],
  'Android Studio': ['android', 'mobile', 'java', 'kotlin'],
  'Kotlin': ['kotlin', 'android', 'mobile'],
  'Swift': ['swift', 'ios', 'mobile', 'apple'],
  'Flutter': ['flutter', 'mobile', 'dart', 'cross-platform'],
  'Xamarin': ['xamarin', 'mobile', 'c#', 'cross-platform'],
  'Objective-C': ['objective-c', 'ios', 'mac', 'apple'],
  'Godot': ['godot', 'game', 'engine', 'development'],
  'IaaS': ['iaas', 'infrastructure', 'cloud'],
  'PaaS': ['paas', 'platform', 'cloud'],
  'SaaS': ['saas', 'software', 'cloud'],
  'Statistical Analysis': ['statistical', 'statistics', 'analysis', 'data'],
  'Intelligent Machines': ['ai', 'intelligent', 'machine', 'automation'],
  'Manufacturing': ['manufacturing', 'production', 'industrial'],
};

export const matchSkillsFromTopic = (topic: string): string[] => {
  if (!topic) return [];
  
  const topicLower = topic.toLowerCase();
  const matchedSkills: Set<string> = new Set();
  
  // Match skills based on keywords
  Object.entries(SKILL_KEYWORDS).forEach(([skill, keywords]) => {
    if (keywords.some(keyword => topicLower.includes(keyword))) {
      matchedSkills.add(skill);
    }
  });
  
  return Array.from(matchedSkills).sort();
};
